name: Upload CloudFormation Template to S3

on:
  push:
    branches:
      - main    # or whichever branch you want to trigger on

jobs:
  upload-template:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: your-aws-region  # e.g. us-east-1

    - name: Upload CloudFormation Template to S3
      run: |
        aws s3 cp ./vpc-template.yaml s3://cloudformation-bucket2k1/vpc-template.yaml